### ISSUE TITLE
consider hyperdrive-next for blob storage

### ISSUE THREAD

**Issue by sethvincent** [digidem/mapeo-core-next#23]
the `diff`, `downloadDiff`, and `downloadRange` methods seem potentially helpful for selective sync of blobs.

https://github.com/hypercore-protocol/hyperdrive-next

**Comment by gmaclennan** [comment]
Great, yes, this is pretty much how I was proposing to implement our blob storage (based on conversations with Mafintosh, so it's not surprising it's the same approach!). What would be helpful though is to store arbitrary metadata with each file entry (which is perfectly possible, because it's just a value in hyperbee). Maybe the Hypercore team would be willing to add this as an option - we could store contentType at least, and maybe other data like geolocation.
I didn't no an update to Hyperdrive was on the cards, and I would say let's use this rather than implement something almost identical ourselves.

**Comment by sethvincent** [comment]
it looks like there's an undocumented ability to store metadata by passing it in the put options: https://github.com/hypercore-protocol/hyperdrive-next/blob/master/index.js#L187

closing this in favor of #52
