### ISSUE TITLE
How do we leave a project?

### ISSUE THREAD

**Issue by achou11** [digidem/mapeo-core-next#241]
## Description

As part of the project api, we want to add a `project.$leave()` method that removes yourself from the project. However, there are some question about what happens internally when doing this:

- can/do we delete project data? maybe some stuff would have to remain in order to inform others that we've left
- do we just write the "blocked" capability for ourself?

**Comment by gmaclennan** [comment]
Initial thoughts are:

- For initial implementation, leave = delete all data (because we won't have a way to delete after, so it will fill up disk space forever)
- Once we track data sync, delete all synced data, but keep unsynced data, however do delete encryption keys (apart from auth key) so that user cannot read it, but they can sync with others (need to implement some kind of "unsynced-data-background-sync")
- I don't think we should write 'blocked' capability for self. Not all users are able to do that. But perhaps we need a new "left" capability, that you can only write about yourself. Would need to keep the auth core around and background sync it with others so that the "left" gets gossiped to everyone. it's helpful it being different I think, because looking at the list of project devices I imagine that a user would want to see the difference between someone being blocked and leaving.

**Comment by ximenabb** [comment]
if we dont do this ticket - workaround to uninstall app but then if the device rejoins the same project theyd be a new device

**Comment by achou11** [comment]
@gmaclennan any preference of wording between "left" and "exited"? currently using "left" but "exited" seems clearer, although more aggressive sounding 😅
