### ISSUE TITLE
Share hypercore keys between peers with hypercore extension

### ISSUE THREAD

**Issue by sethvincent** [digidem/mapeo-core-next#50]
I think this can be written as a class that takes a corestore and a coreId (coreId is `hypercore.key.toString('hex')`) to use as the hypercore for registering the extension.

The class will have method(s) that do the following:
- get keys to share from `CoreIdCache`
- send to connected peers with hypercore extension
- receive keys from connected peers
- dedupe with existing keys in `CoreIdCache`

I'm not entirely sure about the details of implementing this so feel free to adjust the plan if needed.

Initial implementation of this doesn't need to be integrated with the rest of the code, but instead have standalone tests.

**Comment by tomasciccola** [comment]
I'm working this on [https://github.com/digidem/mapeo-core-next/tree/coreReplicator](here).
For now I have a replicate method that recieves a `StoreType` `(auth|data|blob)`, gets all coreIds pertaining that type throught coreIdCache and registers an extension that passes along every coreId when a new peer is connected. 
In this way, the peer that registers the extension is the one that chooses what to replicate (i.e. "I can give you this cores pertaining auth" instead of "Please, give me all the auth cores you have").
This poses the challenge, when receiving a coreId via an extension, how the peer know in which corestore namespace belongs?? We could have some sort of schema and pass json around through the extension. wdyt??

**Comment by sethvincent** [comment]
Nice! I went ahead and made a PR for that branch so I could leave some comments (which I'll do a bit later).

We've got some stacked PRs going now:
- authstore -> main
- sync -> authstore
- coreReplicator -> sync

I can do the work of updating branch bases as things get merged.

**Comment by sethvincent** [comment]
Oh yeah! Though I'd be good with just having one pr that includes both CoreIdCache and CoreReplicator just to make it easier.

**Comment by tomasciccola** [comment]
yeah, that makes sense


> We could have some sort of schema and pass json around through the extension. wdyt??

And what do you think about this??

**Comment by sethvincent** [comment]
Ah, right, so when we receive the message through the extension we need a way to know which namespace the coreIds are in.

Yeah I think it makes sense to have something like:

```js
{
  identityId: '',
  namespace: 'auth' | 'data' | 'blob',
  coreIds: []
}
```

Added the identityId to that as well which could be a useful convenience but might not be necessary if we can get the public key from the peer object which I think is the second argument to `onmessage`.

**Comment by tomasciccola** [comment]
yeah, I should explore more how extensions work and see what we can get from that `peer`. 
I was passing each coreId separately but with this method it makes sense to past a list of them

**Comment by tomasciccola** [comment]
I've done some tests on [this](https://github.com/tomasciccola/mapeo-core-tests) repo. 
peer_1.js creates a core, adds it to the cache and shares it through an extension. 
peer_2.js doesn't share anything and successfully gets the added core key through the extension. 
For these two peers to exchange these messages they need to know beforehand the coreId that registers the extension.
I don't know if the extension needs to be registered on the same core on each side or maybe just doing `store.get({key:masterCore})` on peer_2 would hook up the peer to the extension (it doesn't seem to).

A minor quirk:
the `onmessage` method of the `CoreIdExtension` class is a callback, which means that `this` refers to the hypercore extension, not the class instance, so we can't get any fields from the class (like the corestore).
Of course we could have an anonymous function inside the in the `share` method and do the classic `const self = this`, but I thought I never had to do that again in js xD. 
It would be nice that this callback (`onmessage`) could be a promise so that we can have  a method that, when getting a json through the extension with the corresponding list of coreIds and namespace it just returns it. This way, we don't need corestore as a dependency on CoreIdExtension and someone else can do the store namespace instancing and getting all the cores there.

Gotta think about this a little bit more. 
Also it _feels_ weird that sharing and getting cores goes through the same extension.

**Comment by tomasciccola** [comment]
Mhm, looking at the console output, it seems that they are sharing messages non stop, for some reason...

**Comment by tomasciccola** [comment]
> Ah, right, so when we receive the message through the extension we need a way to know which namespace the coreIds are in.
> 
> Yeah I think it makes sense to have something like:
> 
> ```js
> {
>   identityId: '',
>   namespace: 'auth' | 'data' | 'blob',
>   coreIds: []
> }
> ```
> 
> Added the identityId to that as well which could be a useful convenience but might not be necessary if we can get the public key from the peer object which I think is the second argument to `onmessage`.

In the coreIdCache there's probably going to be distinct identityIds, right? because we can cache and share cores from different peers from one peer. 
Given that, doesn't it make sense to change the CoreIdCache's sql table to store a list of coreIds for a namespace and identityId instead of one coreId per row?
That way when we do `CoreIdExtension.share(type)`, would get a list of `{coreIds:[], namespace, identityId}` that we can send directly as a message through the extension. 
On the other hand, if we save the table with only one coreId when calling share we would need to do something like:
```js
   // first we get a Object with smth like {"identityPublicKey":{coreIds:[], namespace}}
    const mapFromIdentityIds = this.#coreIdCache.getByStoreType(namespace).reduce(
    (acc,record) => {
      if(!acc[record.identityId]){
        acc[record.identityId] = { namespace, coreIds: [] }
      }
      acc[record.identityId].coreIds.push(record.coreId)
      return acc
    }
    , {})
    // then, we turn the Object into an array of objects were the identityId is another field and not the key
    const msg = Object.keys(mapFromIdentityIds)
    .map(k => { return {identityId: k,...mapFromIdentityIds[k]}})

```
which is kind of weird (I mean, we can also do a nested loop to `find` records with the same identityId but I think that would be more expensive)

**Comment by tomasciccola** [comment]
> Given that, doesn't it make sense to change the CoreIdCache's sql table to store a list of coreIds for a namespace and identityId instead of one coreId per row?

there's probably a better way to do this in sqlite, since we have a one (pair of identityId and namespace) to many (coreIds) relationship

**Comment by sethvincent** [comment]
I think it's good to keep the table schema simple. We could get the response from sqlite we want by doing a query that's something like:

```sql
SELECT
  json_group_array(coreId) as coreIds,
  identityId,
  namespace 
FROM table_name 
WHERE identityId = ${identityId} 
GROUP BY identityId, namespace;
```

`json_group_array` is pretty handy for this.

**Comment by gmaclennan** [comment]
Done in #61
