### ISSUE TITLE
Project invites

### ISSUE THREAD

**Issue by sethvincent** [digidem/mapeo-core-next#64]
Our current plan for project invites includes:

- Detecting device presence over mdns
- Sending an invite to a device using information from mdns announcement
- Responding from the invited device to confirm joining
- Optional: a verification step on the device that sent the invite

Implementation would likely include:
- An `MdnsPresence` class that advertises a device on the local network. This can be based on multicast-service-discovery and basically be a simpler version of the mdns stuff that's implemented in the `Discovery` class
- An api for sending/accepting/denying/verifying invites
- This might not require revisions to mapeo-crypto's api, but we'll have to make sure of that: https://github.com/digidem/mapeo-crypto#project-invites

**Comment by gmaclennan** [comment]
Thoughts:
- How to connect to the joiner to send the invite? We could have an http server listening on an open port, or we could make a connection over a hyperswarm secret stream. I think a secret stream might be best — it means we do not have to encrypt the invite (because the stream is encrypted) and it means we can re-use the same connection for initial sync.
- If we use a secret stream connection, then we need to change the project invites in mapeo crypto. We just need a way to encode the project key, project name and (optional?) encryption key to send over the connection stream.
- Maybe eagerly connect to all discovered devices? That way we avoid presenting the user with the option to invite a device that we cannot connect to.
- Do we implement our own protocol to send data over the connection, so that we need to maintain the connection in two states: "inviting" and "hypercore protocol stream", or do we mux the invite data with everything else, either by sending extensions over a "dummy" shared hypercore, or muxing our own channel in protomux? The dummy hypercore seems like overkill, but also the easiest option, so maybe that one? Then we don't have to worry about stream state, we can just replicate everything to the connection and it should just work.
- "Confirmation" in the latter case above could be implicit in the joiner adding the project creator core to the connection stream.
- We need at least the auth cores to complete syncing before the invite is considered "complete", maybe the data cores too?
- I'm not sure we need a verification step. I think that would be a front-end only step, using the public key from the connection to verify the correct device before the invite is actually sent.
