### ISSUE TITLE
Consistent errors / return values for blob getters

### ISSUE THREAD

**Issue by gmaclennan** [digidem/mapeo-core-next#81]
## Description

`blobStore.get()` does not consistently handle errors. Specifically, if data is not available, then sometimes it will return `null` and sometimes it will throw an error.

I think rather than returning `null` at all, it should always throw an error when data is not available and when it is not found.

It may be difficult / impossible to tell the difference between "not found" and "not downloaded" when the blob db has not replicated.

## Tasks

- [ ] Consistently throw an error for either not found blobs or not-downloaded blobs

**Comment by EvanHahn** [comment]
I think this is done because:

1. The code makes it look that way:
   https://github.com/digidem/mapeo-core-next/blob/30e637ba74168d106e17d7b3de349abd97f51c74/src/blob-store/index.js#L99-L101
1. It was checked off in [this GitHub comment](https://github.com/digidem/mapeo-core-next/pull/62#issuecomment-1448901370)
1. I see it in 481c99130e164a9bed6bb4c99964dcb93fa6ffb4

Closing as completed. Let me know if that's wrong and I'll reopen!
